import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar.jsx";
import { Toaster } from "react-hot-toast";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "MHC Frontend Task",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-tertiaryColor text-textPrimary`}>
        <Toaster />
        <section className="w-[98%] m-auto  h-lvh">
          <Navbar />
          {children}
        </section>
      </body>
    </html>
  );
}
